print 'new branch'
print 'master branch fix'
print 'fix conflict'
print 'I want master get my code,I am dev1'
print 'I am master,I have new code'
print 'fix bug ing.........'
print 'I am 2'
print 'bug is fixed'
print 'I am 2 and bug is fixed'
